# Generated by Django 4.1 on 2022-08-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_classe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("origen", models.CharField(max_length=255)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Personagens",
                        to="core.classe",
                    ),
                ),
            ],
        ),
    ]
