# Generated by Django 4.1 on 2022-08-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_personagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personagen",
            name="origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Personagens",
                to="core.origen",
            ),
        ),
    ]
